name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Navigate to the production application directory
            cd /var/www/shopSmart || exit

            # Pull latest changes from master/main
            git pull origin main

            # Install & Build Backend
            cd server
            npm ci
            npm run build

            # Install & Build Frontend
            cd ../client
            npm ci
            npm run build

            # Gracefully restart application manager processes (e.g. pm2)
            # pm2 restart server

            echo "Deployment to EC2 completed successfully!"
