script: |
  # Clone if not exists
  if [ ! -d "/var/www/shopSmart" ]; then
    git clone https://github.com/Shriti507/shopSmart.git /var/www/shopSmart
  fi

  cd /var/www/shopSmart

  # Pull latest code
  git pull origin main

  # backend
  cd server
  npm ci
  npm run build

  # Start/restart backend properly
  pm2 restart shopSmart || pm2 start npm --name "shopSmart" -- start

  # frontend
  cd ../client
  npm ci
  npm run build

  # Deploy frontend to Nginx
  sudo rm -rf /var/www/html/*
  sudo cp -r dist/* /var/www/html/

  # Restart Nginx
  sudo systemctl restart nginx

  echo "Deployment successful"